### ISSUE TITLE
styleSheet declaration causing crash in ReText 3.0

### ISSUE THREAD

**Issue by mitya57** [mitya57/retext#28]
*Imported from https://sourceforge.net/p/retext/tickets/28/*
*Original submitter: Mark Sadecki*

In my ReText.conf file I had the following line:
styleSheet=/home/xxxxxx/css/retext.css

However, this causes the following error upon startup in ReText 3.0:

    Traceback (most recent call last):
      File "/usr/bin/retext", line 1447, in <module>
        main("")
      File "/usr/bin/retext", line 1431, in main
        window = ReTextWindow()
      File "/usr/bin/retext", line 388, in __init__
        ssname = settings.value('styleSheet', type='QString')
    TypeError: QSettings.value(QString, QVariant defaultValue=QVariant()): 'type' is not a valid keyword argument

ReText 2.4 still starts up fine with the same ReText.conf file.  If I comment out that line, ReText 3.0 will start up.

**Comment by mitya57** [comment]
Fixed in f0399133e7be26c2f6dda883574b0811aae01d28.
