### ISSUE TITLE
No module named markups

### ISSUE THREAD

**Issue by mitya57** [mitya57/retext#51]
*Imported from https://sourceforge.net/p/retext/tickets/51/*
*Original submitter: leiking*

```py3tb
Traceback (most recent call last):
  File "./retext.py", line 23, in <module>
    from ReText import *
  File "/home/jinleileiking/tools/git/retext-git/ReText/__init__.py", line 1, in <module>
    import markups
ImportError: No module named markups
```

need some dependencies?

**Comment by mitya57** [comment]
Yes, ReText depends on pymarkups. Use `pip install Markups`.
